### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by TrySound**
Updated dependencies
Removed event-stream
Replaced gulp-util with vinyl

### CODE REVIEW

**Comment by TrySound** [comment]
gulp-if is asleep. So I want to contribute this package.
Can you give me access?

**Comment by nfroidure** [comment]
Hi. Thanks for the PR but some changes aren't following my own conventions. It'll take some time for me to merge it.

gulp-cond is mainly my own toy, nobody uses it so i prefer merge PRs as they are coming since i'll be the only one impacted by changes ;).

**Comment by TrySound** [comment]
I can rewrite with streamtest

**Comment by TrySound** [comment]
@nfroidure Up, please.

**Comment by nfroidure** [comment]
Thanks.

**Pull request merged**
